version: 2
 
sources:
  - name: raw_qwt
    database: "{{env_var('DBT_SOURCEDB', 'QWT_ANALYTICS_DEV')}}"
    schema: "{{env_var('DBT_RAWSCHEMA', 'RAW_DEV')}}"
    tables:
      - name: customers
      
      - name: orders
      
      - name: orderdetails
      - name: raw_employee
      - name: raw_office
      - name: raw_shipment

      - name: raw_suppliers
      